create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  local_report_id bigint unique not null,
  user_id text not null,
  patient_name text not null default '',
  report_date text not null default '',
  lab_name text not null default '',
  report_status text not null default '',
  biomarker_count integer not null default 0,
  source_path text not null default '',
  report_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.biomarker_history (
  id bigint generated by default as identity primary key,
  local_id bigint unique not null,
  user_id text not null,
  local_report_id bigint not null,
  biomarker_name text not null,
  value double precision,
  unit text not null default '',
  flag text not null default '',
  ref_range text not null default '',
  report_date text not null default '',
  lab_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.anomaly_findings (
  id bigint generated by default as identity primary key,
  local_id bigint unique not null,
  user_id text not null,
  biomarker text not null,
  finding_type text not null,
  severity text not null,
  description text not null,
  data_points jsonb not null default '[]'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now()
);

create table if not exists public.share_links (
  id uuid primary key,
  user_id text not null,
  report_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  view_count integer not null default 0
);

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  local_id bigint unique,
  user_id text not null,
  local_report_id bigint not null,
  subject text not null,
  body text not null,
  status text not null default 'queued',
  created_at timestamptz not null default now()
);

alter table public.reports enable row level security;
alter table public.biomarker_history enable row level security;
alter table public.anomaly_findings enable row level security;
alter table public.share_links enable row level security;
alter table public.notification_outbox enable row level security;

create policy "Users can read own reports" on public.reports
  for select using (auth.uid()::text = user_id);

create policy "Users can insert own reports" on public.reports
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update own reports" on public.reports
  for update using (auth.uid()::text = user_id);

create policy "Users can delete own reports" on public.reports
  for delete using (auth.uid()::text = user_id);

create policy "Users can read own biomarker history" on public.biomarker_history
  for select using (auth.uid()::text = user_id);

create policy "Users can insert own biomarker history" on public.biomarker_history
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update own biomarker history" on public.biomarker_history
  for update using (auth.uid()::text = user_id);

create policy "Users can delete own biomarker history" on public.biomarker_history
  for delete using (auth.uid()::text = user_id);

create policy "Users can read own anomaly findings" on public.anomaly_findings
  for select using (auth.uid()::text = user_id);

create policy "Users can insert own anomaly findings" on public.anomaly_findings
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update own anomaly findings" on public.anomaly_findings
  for update using (auth.uid()::text = user_id);

create policy "Users can delete own anomaly findings" on public.anomaly_findings
  for delete using (auth.uid()::text = user_id);

create policy "Users can read own share links" on public.share_links
  for select using (auth.uid()::text = user_id);

create policy "Users can insert own share links" on public.share_links
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update own share links" on public.share_links
  for update using (auth.uid()::text = user_id);

create policy "Users can delete own share links" on public.share_links
  for delete using (auth.uid()::text = user_id);

create policy "Users can read own notifications" on public.notification_outbox
  for select using (auth.uid()::text = user_id);

create policy "Users can insert own notifications" on public.notification_outbox
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update own notifications" on public.notification_outbox
  for update using (auth.uid()::text = user_id);

create policy "Users can delete own notifications" on public.notification_outbox
  for delete using (auth.uid()::text = user_id);

insert into storage.buckets (id, name, public)
values ('User Data', 'User Data', false)
on conflict (id) do nothing;

create policy "Users can read own uploaded files" on storage.objects
  for select using (
    bucket_id = 'User Data'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "Users can upload own files" on storage.objects
  for insert with check (
    bucket_id = 'User Data'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "Users can update own files" on storage.objects
  for update using (
    bucket_id = 'User Data'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "Users can delete own files" on storage.objects
  for delete using (
    bucket_id = 'User Data'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
